# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'false'  # Cache désactivé temporairement pour éviter des soucis

    - name: Install root dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: npm ci --prefix Frontend

    - name: List files in the repository
      run: ls -R  # Vérifie la structure des fichiers et si 'Frontend/package.json' existe

    - name: Run ESLint on frontend
      run: npm run lint --prefix Frontend

    - name: Run build frontend
      run: npm run build:frontend --prefix Frontend

    - name: Run tests frontend
      run: npm test --prefix Frontend

    - name: Install backend dependencies
      run: npm ci --prefix Backend

    - name: Run ESLint on backend
      run: npm run lint --prefix Backend

    - name: Run build backend
      run: npm run build:backend --prefix Backend

    - name: Run tests backend
      run: npm test --prefix Backend


   

 
